version: "3"

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/oada-ensure:/code/oada-ensure

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/oada-ensure:/code/oada-ensure


  ###############################################
  # This service's definition:
  ###############################################
  oada-ensure:
    depends_on:
      - startup
    build:
      context: ./services-available/oada-ensure
    container_name: oada-ensure
    restart: always
    networks:
      - startup_net
    volumes:
      - ./services-available/oada-ensure:/code/oada-ensure
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG
      - domain
      - token
